theme: minima
title: Getting to know GitHub Pages
author: Kimberley
email: kim_greenbush@icloud.com
description: > # this means to ignore newlines until "baseurl:"
  This site is a tutorial for learning about GitHub Pages.

# social links
github_username:  KimGreenbush # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
